import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <header className="border-b">
          <nav className="container mx-auto px-4 py-3">
            <Link href="/" className="font-bold text-xl">
              SpectraNet
            </Link>
            <Link href="/login">
  Login
</Link>
<Link href="/dashboard">Dashboard</Link>
<Link href="/profile">Profile</Link>
<Link href="/data-plans">Data Plans</Link>
<Link href="/usage-history">Usage History</Link>
<Link href="/payments">Payments</Link>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
